### ISSUE TITLE
TODO: Add support for dropping DBs

### ISSUE THREAD

**Issue by vot** [vot/dbclone#2]

**Comment by Dikaeinstein** [comment]
@vot I can handle this

**Comment by vot** [comment]
Hi @Dikaeinstein,

First of all thanks for offering help :)

So the idea I had in mind for this is the following:
- implementing dropDatabase in mongo driver
- add `lib/drop.js` and bind it in `cli.js` and `index.js`

If you run `dbclone drop --host x --name x` it should simply drop the selected database (or indicate that db doesn't exist).

Does this make enough sense?

**Comment by Dikaeinstein** [comment]
@vot Sorry for the late reply, I think the explanation is clear enough. I will reach out to you if I need more context or face blockers.

**Comment by vot** [comment]
No problem @Dikaeinstein, all help is appreciated regardless of timing. Happy Hacktoberfest! :)

**Comment by Dikaeinstein** [comment]
@vot The PR for drop database is up. Review and merge, if you consider it good enough. Feedback is always welcomed.

**Comment by vot** [comment]
@Dikaeinstein PR reviewed and merged :)
