### ISSUE TITLE
TODO: Add document count

### ISSUE THREAD

**Issue by vot** [vot/dbclone#3]

**Comment by bhagatparwinder** [comment]
@vot I can do this. Can you provide some more description in the ticket?

**Comment by vot** [comment]
Hi @bhagatparwinder Sure, I just started creating the issues (probably should've filled in the details first before tagging them :) ).

The idea is to allow printing out something like this after a successful import/export/diff operation:

```
|-----------------------|
|collection |documents  |
|-----------|-----------|
|files      |        10 |
|pages      |        30 |
|-----------------------|
```
