### ISSUE TITLE
TODO: Write better documentation

### ISSUE THREAD

**Issue by vot** [vot/dbclone#5]
We need JSDoc standard documentation for methods written here.
The coverage of that is not great at the moment and what's there is potentially outdated.

Read the code and fill in the missing JSDoc above functions and review existing JSDoc comments :)

**Comment by martalais** [comment]
I've add some comments at the backend files, fs.js and mongo.js. Hope it helps. =)

**Comment by vot** [comment]
Hi @martalais,

I've just started reviewing the PR - thanks for contributing :) I'll put a few comments alongside the PR.

And yes - every small update is helpful as I haven't been able to put enough time into this lib.

Happy Hacktoberfest!

**Comment by YuechengWu** [comment]
Hi @vot, when you say better documentation, are there specific documentations that you want to improve, or just anything will do?

**Comment by vot** [comment]
So at the moment there isn't a whole lot of documentation here so anything will do really at this point.
@martalais has started putting better comments in the source code itself.

I think right now this could use some documentation of the backend (which is currently pretty much just Mongo and file system). Describing methods in a readme and how to use them would go a long way.

The idea is to have multiple backends (right now I'm mostly concerned about MongoDB, Redis and MySQL) so documenting what each backend can/should expose would be incredibly helpful.

This will require reading through the files ;)

**Comment by YuechengWu** [comment]
@vot, let me try my best and help with this issue if you allow me, thanks.
